language: ruby

rvm:
  - 1.9.3
  - 2.0.0

notifications:
  email:
    recipients:
      - weston@think602.com
    on_success: [change]
    on_failure: [always]

before_script: bundle exec rake dummy:app
